FROM docker.io/ruby:2.7 as builder
COPY . /src
WORKDIR /src
RUN gem install bundler -v 2.3.27
RUN bundle install
RUN bundle exec jekyll build

FROM docker.io/nginx:latest
COPY --from=builder /src/_site/ /usr/share/nginx/html/
